Repository rizkytegar/veonote, pull requests merged in 2023-10, with the labels that each got.

#3 🚀 upload project : vite + typescript
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
Labels: hacktoberfest-accepted, hacktoberfest

#5 🚀 Update project name
  index.html
  package-lock.json
  package.json
Labels: hacktoberfest-accepted, hacktoberfest

#7 🚀 Adding Date (Day, Month, Year) #4
  src/App.tsx
  src/index.css
Labels: hacktoberfest-accepted, hacktoberfest

#8 Migrate To Vite and Typescript #2
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.tsx
  src/index.css
  tailwind.config.js
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#10 🚀 add Daisy UI, change Theme and Color
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/SelectTimeZone.tsx
  src/index.css
  src/main.tsx
  src/style.css
  tailwind.config.js
Labels: hacktoberfest-accepted, hacktoberfest

#11 🚀 Add National Holidays
  src/App.tsx
  src/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#14 Code Refactoring and Structure Improvement #12
  src/App.tsx
  src/components/DigitalClock.tsx
  src/components/TimeZoneSelector.tsx
  src/main.tsx
  src/styles/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#16 adding loading from ammar
  src/App.tsx
  src/components/DigitalClock.tsx
  src/components/TimeZoneSelector.tsx
  src/styles/style.css
Labels: Under Review, hacktoberfest
